### PR TITLE
Add persistence api and small improvements

### PR DESCRIPTION
**Pull request by bmihovski**
Here are the persistence plugin and small improvements. 
Unfortunately auto formatting was applied according to lua standards. I hope will be not a big issue. However, keeping standard formatting could bring benefits when more contributors.

In my case is configured liketthat

```lua

  -- Custom Formatters
	{
		"stevearc/conform.nvim",
		lazy = true,
		event = "LspAttach",
		config = function()
			require("conform").setup({
				formatters_by_ft = {
					lua = { "stylua" },
```

### CODE REVIEW

**Comment by imbacraft** [comment]
@bmihovski Thank you for the PR. Can you describe the small improvements, since I cannot spot them in the "changed files" section?

**Comment by bmihovski** [comment]
You are very welcome! Dap ui auto open and close plugin setup is added. Tmux integration is added currently commented is up to the l user to enabled (similar to the lint plugin). Probably deleted by accident plugin (it still available in telescope setup)  smartpde/telescope-recent-files is added again.

**Comment by imbacraft** [comment]
I intentionally left out smartpde/telescope-recent-files extension, because its appearance cannot be customized. I want to have previewer = false in my file pickers, and this extension did not allow me to do that.

**Comment by bmihovski** [comment]
@imbacraft thank you for merging the pr. Feel free to remove the telescope extension then. Do we have an alternative of it preinstalled?
One more thing I have github copilot with chat integrated with dusk . Let me know if you think we should have it as commented out plugin and I can create a PR with it.

**Pull request merged**
